/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { SubscriptionPreset } from './types';

export const SUBSCRIPTION_PRESETS: SubscriptionPreset[] = [
  {
    name: 'Netflix',
    defaultPrice: 15.49,
    currency: 'USD',
    cycle: 'monthly',
    category: 'Entertainment',
    paymentMethod: 'Credit Card',
    color: '#E50914',
    emoji: '🍿',
  },
  {
    name: 'Spotify Premium',
    defaultPrice: 11.99,
    currency: 'USD',
    cycle: 'monthly',
    category: 'Entertainment',
    paymentMethod: 'PayPal',
    color: '#1DB954',
    emoji: '🎵',
  },
  {
    name: 'ChatGPT Plus',
    defaultPrice: 20.00,
    currency: 'USD',
    cycle: 'monthly',
    category: 'Productivity',
    paymentMethod: 'Credit Card',
    color: '#10A37F',
    emoji: '🤖',
  },
  {
    name: 'YouTube Premium',
    defaultPrice: 13.99,
    currency: 'USD',
    cycle: 'monthly',
    category: 'Entertainment',
    paymentMethod: 'Google Pay',
    color: '#FF0000',
    emoji: '📺',
  },
  {
    name: 'Apple One',
    defaultPrice: 19.95,
    currency: 'USD',
    cycle: 'monthly',
    category: 'Entertainment',
    paymentMethod: 'Apple Pay',
    color: '#000000',
    emoji: '🍎',
  },
  {
    name: 'iCloud+',
    defaultPrice: 6.00,
    currency: 'CNY',
    cycle: 'monthly',
    category: 'Cloud',
    paymentMethod: 'Apple Pay',
    color: '#007AFF',
    emoji: '☁️',
  },
  {
    name: 'GitHub Copilot',
    defaultPrice: 10.00,
    currency: 'USD',
    cycle: 'monthly',
    category: 'Productivity',
    paymentMethod: 'Credit Card',
    color: '#24292F',
    emoji: '💻',
  },
  {
    name: 'Bilibili 大会员',
    defaultPrice: 25.00,
    currency: 'CNY',
    cycle: 'monthly',
    category: 'Entertainment',
    paymentMethod: 'WeChat Pay',
    color: '#FB7299',
    emoji: '⚡',
  },
  {
    name: '腾讯视频 VIP',
    defaultPrice: 30.00,
    currency: 'CNY',
    cycle: 'monthly',
    category: 'Entertainment',
    paymentMethod: 'Alipay',
    color: '#FF7F00',
    emoji: '🎬',
  },
  {
    name: '网易云音乐黑胶 VIP',
    defaultPrice: 18.00,
    currency: 'CNY',
    cycle: 'monthly',
    category: 'Entertainment',
    paymentMethod: 'WeChat Pay',
    color: '#E60026',
    emoji: '🎧',
  },
  {
    name: 'Notion Plus',
    defaultPrice: 10.00,
    currency: 'USD',
    cycle: 'monthly',
    category: 'Productivity',
    paymentMethod: 'Credit Card',
    color: '#000000',
    emoji: '📝',
  },
  {
    name: 'Midjourney',
    defaultPrice: 30.00,
    currency: 'USD',
    cycle: 'monthly',
    category: 'Productivity',
    paymentMethod: 'Credit Card',
    color: '#5B4CF5',
    emoji: '🎨',
  },
  {
    name: 'Xbox Game Pass',
    defaultPrice: 16.99,
    currency: 'USD',
    cycle: 'monthly',
    category: 'Entertainment',
    paymentMethod: 'Credit Card',
    color: '#107C10',
    emoji: '🎮',
  },
  {
    name: 'Adobe Creative Cloud',
    defaultPrice: 54.99,
    currency: 'USD',
    cycle: 'monthly',
    category: 'Productivity',
    paymentMethod: 'Credit Card',
    color: '#FF0000',
    emoji: '🖌️',
  },
  {
    name: '任天堂 Switch Online',
    defaultPrice: 20.00,
    currency: 'USD',
    cycle: 'yearly',
    category: 'Entertainment',
    paymentMethod: 'PayPal',
    color: '#E60012',
    emoji: '🕹️',
  },
  {
    name: '服务器/域名主机',
    defaultPrice: 99.00,
    currency: 'CNY',
    cycle: 'yearly',
    category: 'Cloud',
    paymentMethod: 'Alipay',
    color: '#3B82F6',
    emoji: '🖥️',
  }
];
